[programs.devnet]
project_registry = "Dkrnk6B8MuiieXQzqhicbsPtGp7TY4HMZRNDJJFhu4R7"
compliance_transfer = "CHWFf4LBaq3VECZ6hiH4YZWNrqezkDteiDq1VbYLFtTs"
allocation_distribution = "GG9mE55B6mMJFSY8RYVjCt62THVVrMjv55pVzHsZs8nT"

[provider]
cluster = "devnet"


[scripts]
test = "mocha -t 1000000 tests/**/*.ts"
